#!/usr/bin/env node
// scripts/readme-check.mjs
//
// GRADE THIS REPOSITORY'S OWN READMEs AGAINST THE HOUSE SKELETON, SO THE SHAPE IS ENFORCED RATHER
// THAN ASSERTED.
//
// THE DEFECT THIS EXISTS FOR. This repository publishes eight `@cosyte/*` packages and a README is
// inside every one of their `files` arrays, so the text is FROZEN INTO THE TARBALL at publish time
// and a wrong string can be corrected only by publishing again. Before this gate, not one of the
// nine READMEs carried the Cosyte banner, a badge row, a tagline, or the `Why this exists`,
// `Status`, `PHI and safety`, `Contributing` or `License` sections, and the repo README pointed a
// public reader at an internal path that does not exist. A reader arriving from npm got an
// unbranded page that could not tell them what the package claims or whether it is safe to depend
// on. Rewriting the nine files fixes the instance. This fixes the class.
//
// SCOPE, STATED SO IT IS NOT ASSUMED. This grades THIS repository's own READMEs only. It is not the
// estate-wide README gate and it deliberately does not read `drift-manifest.json`: generalizing the
// shape to the other repos is a separate change with its own operator-derived provenance note.
//
// THE GOVERNED SET IS DERIVED FROM THE WORKSPACE AT RUN TIME, NEVER HARDCODED, and that is the half
// of this gate that keeps working after it is written. A hardcoded list of nine paths grades nine
// paths forever: add a tenth package with no README and the gate stays green over it, which is the
// silent-skip shape every other gate in this repo is built to refuse. So the set is the root plus
// every directory under `packages/` that carries a `package.json`, and a governed README that is
// absent is a REFUSAL rather than a skip.
//
// WHAT "BYTE-IDENTICAL" MEANS FOR THE DESCRIPTION, because this is the one place where a literal
// reading would be wrong. Prettier owns markdown formatting in this repo and it ESCAPES markdown
// punctuation in prose: every one of the nine descriptions contains `@cosyte/*`, and Prettier
// rewrites that to `@cosyte/\*`. Measured, not predicted. So the README line is unescaped back to
// its rendered text before it is compared to `package.json`'s `description`, and the comparison is
// then byte-for-byte with no normalization of case, spacing or punctuation. Fighting Prettier here
// would mean a gate that reds on `pnpm format`, which is a gate nobody keeps.
//
// A PROSE CLAIM IS READ OUT OF THE PROSE, NOT OUT OF A URL. Every README here ends with the ABSOLUTE
// link to the repo-root `LICENSE` the house skeleton mandates, and that URL contains the owner's own
// name: `https://github.com/cosyte/config/blob/main/LICENSE`. A check that searched the raw section
// for `Cosyte` therefore passed on a README crediting NOBODY, which made the attribution
// requirement unfailable for exactly the eight files that reach npm. So the `## License` claims are
// graded against `stripLinkTargets()` output: labels a reader sees survive, and destinations,
// reference definitions, autolinks, bare URLs and HTML link attributes do not.
//
// Usage:
//   node scripts/readme-check.mjs [--workspace <repo-root>]
//
// Exit codes, which are a contract and are asserted by test/readme-check.test.ts:
//   0  every governed README carries the house skeleton
//   1  at least one governed README violates it (the refusal this gate exists for)
//   2  the check could not run (bad invocation, a governed README absent or unreadable, a
//      `package.json` beside one missing or unparseable, a workspace layout this cannot ground on)
//
// The 1-versus-2 split is the same contract scripts/changeset-guard.mjs holds and it matters for
// the same reason: a gate that cannot read its input must not report the same code as a gate that
// read it and found a violation, or "broken" and "caught something" become one signal in CI. A
// checker that cannot ground its own premise NEVER reports clean.

import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";

// Imported by RELATIVE PATH, not as `@cosyte/script-utils`, for the same reason
// scripts/changeset-guard.mjs does it: the gates in this repo run before `pnpm install` in CI, so
// there is no `node_modules` for a bare specifier to resolve through. Same file, same contents,
// published for the other repos to use.
import { isCliEntrypoint } from "../packages/script-utils/index.js";

/** Thrown for an invocation or environment problem: exit 2, never exit 1. */
class InvocationError extends Error {}

/**
 * The Cosyte banner, required byte-identical and first in every governed README.
 *
 * The tiles are GENERATED by the assets repo and the alt string is central in its `alt-text.json`,
 * so neither is hand-written here: this constant is a copy of the declaration, and a README that
 * disagrees with it is the thing being refused. The URLs stay ABSOLUTE because npm does not resolve
 * relative images, and the `<img>` fallback carries the LIGHT tile so a renderer that drops
 * `<source>` still shows something.
 */
export const BANNER = [
  '<a href="https://cosyte.com">',
  "  <picture>",
  '    <source media="(prefers-color-scheme: dark)" srcset="https://cosyte.com/tile/cosyte-lockup-tile-on-dark-1200x300.png">',
  '    <img alt="The Cosyte logo on its own white ground: the icon beside the word Cosyte." src="https://cosyte.com/tile/cosyte-lockup-tile-on-light-1200x300.png">',
  "  </picture>",
  "</a>",
].join("\n");

/** Where a reader is told to ask. Required in every `## Contributing` section. */
export const ISSUES_URL = "https://github.com/cosyte/config/issues";

/** The CI badge, identical in all nine files. */
const CI_BADGE =
  "[![CI](https://img.shields.io/github/actions/workflow/status/cosyte/config/ci.yml?branch=main&label=CI)](https://github.com/cosyte/config/actions/workflows/ci.yml)";

/**
 * The License badge. Its target is ABSOLUTE because no package ships its own `LICENSE` file (the
 * only one is at the repo root), so a relative link would break on npm.
 */
const LICENSE_BADGE =
  "[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://github.com/cosyte/config/blob/main/LICENSE)";

/**
 * The required `##` headings, in the order they must appear. `## License` is additionally required
 * to be the LAST heading in the file. Other headings (`## API`, `## Compatibility`, and anything
 * else a package needs) may sit between them; what is graded is that these seven are present, in
 * this relative order, and that License closes the file.
 */
export const REQUIRED_HEADINGS = [
  "Why this exists",
  "Status",
  "Install",
  "Usage",
  "PHI and safety",
  "Contributing",
  "License",
];

/** A tagline is a hook, not a paragraph. The template's ceiling. */
const TAGLINE_LIMIT = 120;

/** GitHub truncates past this, so a README that exceeds it stops being readable where it matters. */
const SIZE_LIMIT_BYTES = 500 * 1024;

/**
 * Umbrella meta-repo surfaces a PUBLIC reader must never be pointed at.
 *
 * Note what is NOT here: a bare `documentation/` path. This repository has its own `documentation/`
 * directory holding its ADRs, and those pointers are legitimate and are preserved. What is refused
 * is a path that only exists inside the private meta-repo, of which
 * `documentation/conventions.md` is the one this repo actually shipped: it does not exist, and by
 * operator decision none is to be written. The standard these packages encode is
 * `drift-manifest.json`, which says so itself.
 */
const UMBRELLA_REFERENCES = [
  [/documentation\/conventions\.md/i, "documentation/conventions.md"],
  [/\bmeta-repo\b/i, "meta-repo"],
  [/\bmeta repo\b/i, "meta repo"],
  [/\bumbrella repo(?:sitory)?\b/i, "umbrella repo"],
  [/\bwork\/(?:specs|backlog|inbox|archive)\//i, "work/ stage directory"],
  [/sdd-umbrella-blueprint/i, "sdd-umbrella-blueprint"],
  [/\bcards\/[a-z0-9][a-z0-9-]*\.md\b/i, "cards/<repo>.md"],
];

/**
 * Release-cadence, release-frequency and support-window claims.
 *
 * `S0161-release-frequency-policy` owns that policy and has not landed, so a README that guesses it
 * would have to be rewritten when it does. Stated honestly: this is a keyword tripwire over the
 * phrases a README plausibly uses, not a semantic classifier. It cannot catch a cadence expressed in
 * a sentence nobody anticipated, and it is not claimed to. It errs toward refusing, which is the
 * safe direction for a string that publishes to npm.
 */
const CADENCE_CLAIMS = [
  [/\brelease cadence\b/i, "a release cadence"],
  [/\brelease schedule\b/i, "a release schedule"],
  [/\breleas(?:e|ed|es) (?:every|each) \w+/i, "a release frequency"],
  [
    /\b(?:weekly|monthly|quarterly|biweekly|fortnightly|nightly|daily) releases?\b/i,
    "a release frequency",
  ],
  [/\bevery (?:\d+|two|three|four|six|twelve) (?:days?|weeks?|months?)\b/i, "a release frequency"],
  [/\bsupport window\b/i, "a support window"],
  [/\bmaintenance window\b/i, "a support window"],
  [/\bsupported (?:for|until)\b/i, "a support window"],
  [/\bend[- ]of[- ]life\b/i, "a support window"],
  [/\bsupport(?:s|ed)? (?:for )?\d+ (?:months?|years?)\b/i, "a support window"],
];

/** Claims a `0.0.x` package's README must not make about its public API. */
const SETTLED_API_CLAIMS = [
  /\b(?:public )?API is (?:settled|stable|frozen|final)\b/i,
  /\bstable (?:public )?API\b/i,
  /\bsettled (?:public )?API\b/i,
  /\bsafe to depend on\b/i,
  /\bAPI (?:will not|won't) change\b/i,
];

/**
 * Undo the markdown escaping Prettier applies to prose.
 *
 * CommonMark lets a backslash escape any ASCII punctuation character, and that is exactly the set
 * Prettier reintroduces. Undoing it is what makes the description comparison a comparison of
 * RENDERED TEXT rather than of source bytes, which is the only version of "identical to the
 * manifest string" that survives `pnpm format`.
 *
 * @param {string} value Markdown source text.
 * @returns {string} The text as it renders.
 */
export function unescapeMarkdown(value) {
  return value.replace(/\\([!"#$%&'()*+,\-./:;<=>?@[\]^_`{|}~\\])/g, "$1");
}

/**
 * Markdown with every link and image TARGET removed, leaving the text a reader actually sees.
 *
 * WHY THIS EXISTS, written down so it is not simplified away. A URL is machine address, not prose,
 * and the two must never be confused when what is being graded is a CLAIM THE README MAKES. The
 * `## License` section of all eight published READMEs ends with the absolute link this repository
 * mandates, `https://github.com/cosyte/config/blob/main/LICENSE`, and the owner's name sits inside
 * that URL. Searching the raw section for `Cosyte` therefore matched the address rather than the
 * attribution, so the owner requirement could not fail on any README carrying the link the skeleton
 * REQUIRES: the check was dead code on precisely the files that publish. Deleting the attribution
 * left the gate green. What survives here is what a reader reads: link and image LABELS, and prose.
 * What goes is every address: inline destinations and titles, reference definitions, autolinks,
 * bare URLs, and the HTML attributes that carry a target.
 *
 * Each target becomes a SPACE rather than nothing, so stripping can never fuse two words into a
 * third that neither of them was.
 *
 * @param {string} value Markdown source text.
 * @returns {string} The same text with link targets removed.
 */
export function stripLinkTargets(value) {
  return (
    value
      // `[label]: https://example.com "title"` reference definitions, which are pure address.
      .replace(/^ {0,3}\[[^\]]*\]:.*$/gm, " ")
      // `[label](destination "title")` and `![alt](destination)`; the label and alt survive.
      .replace(/\]\((?:[^()\\]|\\.|\([^()]*\))*\)/g, "] ")
      // `<https://example.com>` and `<user@example.com>` autolinks.
      .replace(/<(?:[a-z][a-z0-9+.-]*:|[^\s<>@]+@)[^\s<>]*>/gi, " ")
      // HTML attributes that carry a target. `alt` is deliberately NOT here: it is read aloud.
      .replace(
        /\b(?:href|src|srcset|cite|action|formaction|poster|data)\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,
        " ",
      )
      // A bare URL pasted into prose.
      .replace(/\b(?:[a-z][a-z0-9+.-]*:\/\/|www\.)\S+/gi, " ")
  );
}

/**
 * Mark every line that sits inside a fenced code block.
 *
 * Headings are only headings outside a fence. This repo's own READMEs already contain fenced blocks
 * that hold `#` comment lines and a nested ```` ```md ```` fence, so a naive line scan would invent
 * headings that no reader sees.
 *
 * @param {string[]} lines The file's lines.
 * @returns {boolean[]} One flag per line: `true` when the line is a fence delimiter or inside one.
 */
export function fenceMask(lines) {
  const mask = new Array(lines.length).fill(false);
  let openFence = null;
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i] ?? "";
    const match = /^ {0,3}(`{3,}|~{3,})/.exec(line);
    if (openFence === null) {
      if (match !== null) {
        openFence = match[1] ?? "";
        mask[i] = true;
      }
      continue;
    }
    mask[i] = true;
    if (
      match !== null &&
      (match[1] ?? "").charAt(0) === openFence.charAt(0) &&
      (match[1] ?? "").length >= openFence.length &&
      line.trim() === (match[1] ?? "")
    ) {
      openFence = null;
    }
  }
  return mask;
}

/**
 * The `##` headings of a README, in file order, with the line range each one owns.
 *
 * @param {string[]} lines The file's lines.
 * @param {boolean[]} mask The fence mask.
 * @returns {{ title: string, line: number, start: number, end: number }[]} Sections in file order.
 */
export function sectionsOf(lines, mask) {
  const found = [];
  for (let i = 0; i < lines.length; i += 1) {
    if (mask[i] === true) continue;
    const match = /^## +(.+?)\s*$/.exec(lines[i] ?? "");
    if (match !== null)
      found.push({ title: (match[1] ?? "").trim(), line: i, start: i + 1, end: 0 });
  }
  for (let i = 0; i < found.length; i += 1) {
    const next = found[i + 1];
    const current = found[i];
    if (current !== undefined) current.end = next === undefined ? lines.length : next.line;
  }
  return found;
}

/**
 * Index of the next line at or after `from` that holds something other than whitespace.
 *
 * @param {string[]} lines The file's lines.
 * @param {number} from Where to start looking.
 * @returns {number} The index, or `lines.length` when there is none.
 */
function nextNonBlank(lines, from) {
  let i = from;
  while (i < lines.length && (lines[i] ?? "").trim() === "") i += 1;
  return i;
}

/**
 * The run of consecutive non-blank lines starting at `from`.
 *
 * @param {string[]} lines The file's lines.
 * @param {number} from Where the block starts.
 * @returns {string[]} The block's lines.
 */
function blockAt(lines, from) {
  const block = [];
  let i = from;
  while (i < lines.length && (lines[i] ?? "").trim() !== "") {
    block.push(lines[i] ?? "");
    i += 1;
  }
  return block;
}

/**
 * A package's EFFECTIVE Node floor: its own declared range when it has one, the root's otherwise.
 *
 * The floors in this workspace genuinely DIVERGE and this gate does not reconcile them; changing a
 * published package's declared engine range is a behaviour change with a changeset. What is graded
 * is that a README REPORTS what is true of its own package today.
 *
 * @param {Record<string, unknown>} manifest The package manifest.
 * @param {string} rootFloor The root manifest's `engines.node`.
 * @returns {string} The effective floor, for example `>=22.14`.
 */
export function effectiveFloor(manifest, rootFloor) {
  const engines = manifest.engines;
  if (engines !== null && typeof engines === "object" && typeof engines.node === "string") {
    return engines.node;
  }
  return rootFloor;
}

/**
 * The Node badge for a floor, in the URL-encoded form shields.io needs.
 *
 * @param {string} floor The effective floor, for example `>=22.14`.
 * @returns {string} The badge line.
 */
export function nodeBadge(floor) {
  const label = `node-${floor.replaceAll(">", "%3E").replaceAll("=", "%3D")}`;
  return `[![Node](https://img.shields.io/badge/${label}-brightgreen.svg)](https://nodejs.org)`;
}

/**
 * The house badge row for one package, in the required order.
 *
 * The npm version badge is present IF AND ONLY IF the package publishes. The root manifest is
 * `private: true`, so no npm page exists to link and a version badge there would render broken
 * forever.
 *
 * @param {{ name: string, isPrivate: boolean, floor: string }} pkg The package's facts.
 * @returns {string[]} The expected badge lines, in order.
 */
export function expectedBadges({ name, isPrivate, floor }) {
  const badges = [];
  if (!isPrivate) {
    badges.push(
      `[![npm version](https://img.shields.io/npm/v/${name}.svg)](https://www.npmjs.com/package/${name})`,
    );
  }
  badges.push(CI_BADGE, LICENSE_BADGE, nodeBadge(floor));
  return badges;
}

/**
 * The exact Status sentence a `0.0.x` package's README must open its `## Status` section with.
 *
 * When a package is bumped to 0.1.0 this sentence is replaced with the settled-API claim the
 * template calls for. Until then it is the honest one, and it is mechanically checkable.
 *
 * @param {string} name The package name from its own manifest.
 * @returns {string} The sentence.
 */
export function statusSentence(name) {
  return `\`${name}\` is on the cosyte 0.0.x ladder: the public API is not yet settled and may change in any release.`;
}

/**
 * Grade one README against the house skeleton.
 *
 * Every problem the file has is collected: grading stops at no first failure, because a reader
 * fixing one element wants to see the rest in the same run rather than one per push.
 *
 * @param {object} entry The governed entry.
 * @param {string} entry.label The README's repo-relative path, for diagnostics.
 * @param {string} entry.text The file contents.
 * @param {Record<string, any>} entry.manifest The `package.json` beside it.
 * @param {string} entry.floor The effective Node floor.
 * @returns {string[]} One line per problem. Empty means the README conforms.
 */
export function gradeReadme({ label, text, manifest, floor }) {
  const problems = [];
  const say = (element, detail) => problems.push(`${label}: ${element}: ${detail}`);

  const name = typeof manifest.name === "string" ? manifest.name : "";
  const version = typeof manifest.version === "string" ? manifest.version : "";
  const description = typeof manifest.description === "string" ? manifest.description : "";
  const isPrivate = manifest.private === true;

  const bytes = Buffer.byteLength(text, "utf8");
  if (bytes > SIZE_LIMIT_BYTES) {
    say("size", `${bytes} bytes exceeds the ${SIZE_LIMIT_BYTES}-byte ceiling; GitHub truncates it`);
  }

  const lines = text.split("\n");
  const mask = fenceMask(lines);

  // --- BANNER, byte-identical and first in the file -------------------------------------------
  const bannerLines = BANNER.split("\n");
  const head = lines.slice(0, bannerLines.length).join("\n");
  if (head !== BANNER) {
    say(
      "banner",
      "the file does not open with the Cosyte banner byte-identical to the house block " +
        "(dark-scheme <source>, light-tile <img> fallback, absolute https://cosyte.com/tile/ URLs, " +
        "and the central alt string). Never hand-write the alt text",
    );
  }

  // Relative image sources break on npm, which does not resolve them against the repo.
  for (let i = 0; i < lines.length; i += 1) {
    if (mask[i] === true) continue;
    const line = lines[i] ?? "";
    const sources = [
      ...[...line.matchAll(/<img\b[^>]*?\bsrc="([^"]*)"/gi)].map((m) => m[1] ?? ""),
      ...[...line.matchAll(/<source\b[^>]*?\bsrcset="([^"]*)"/gi)].map((m) => m[1] ?? ""),
      ...[...line.matchAll(/!\[[^\]]*\]\(([^)\s]+)/g)].map((m) => m[1] ?? ""),
    ];
    for (const source of sources) {
      if (!/^(?:https?:|data:)/i.test(source)) {
        say(
          "images",
          `line ${i + 1} carries the relative image source ${JSON.stringify(source)}; npm does not resolve it`,
        );
      }
    }
  }

  // --- H1, tagline, badges, description, in file order ----------------------------------------
  const h1Lines = [];
  for (let i = 0; i < lines.length; i += 1) {
    if (mask[i] !== true && /^# +\S/.test(lines[i] ?? "")) h1Lines.push(i);
  }
  if (h1Lines.length !== 1) {
    say("h1", `the file carries ${h1Lines.length} level-1 headings; exactly one is required`);
  }

  const h1 = h1Lines[0];
  if (h1 !== undefined) {
    for (let i = bannerLines.length; i < h1; i += 1) {
      if ((lines[i] ?? "").trim() !== "") {
        say("h1", `line ${i + 1} sits between the banner and the H1; nothing may`);
        break;
      }
    }

    const taglineStart = nextNonBlank(lines, h1 + 1);
    const taglineBlock = blockAt(lines, taglineStart);
    if (taglineBlock.length === 0 || !/^> /.test(taglineBlock[0] ?? "")) {
      say("tagline", "the H1 is not followed by a one-line blockquote tagline");
    } else if (taglineBlock.length > 1) {
      say("tagline", `the tagline runs ${taglineBlock.length} lines; it must be one`);
    } else {
      const tagline = (taglineBlock[0] ?? "").replace(/^> /, "");
      if (tagline.length >= TAGLINE_LIMIT) {
        say("tagline", `${tagline.length} characters; the ceiling is ${TAGLINE_LIMIT}`);
      }
    }

    const badgeStart = nextNonBlank(lines, taglineStart + taglineBlock.length);
    const badgeBlock = blockAt(lines, badgeStart);
    const wanted = expectedBadges({ name, isPrivate, floor });
    if (badgeBlock.join("\n") !== wanted.join("\n")) {
      say(
        "badges",
        `the badge row must be exactly these ${wanted.length}, in this order (npm version` +
          `${isPrivate ? " omitted: this package is private" : ""}, CI, License, Node):\n` +
          `${wanted.map((b) => `    want: ${b}`).join("\n")}\n` +
          `${badgeBlock.map((b) => `    got:  ${b}`).join("\n") || "    got:  (no badge row)"}`,
      );
    }

    // A shields badge anywhere else in the file is a fifth badge wearing a different position.
    for (let i = 0; i < lines.length; i += 1) {
      if (mask[i] === true) continue;
      if (i >= badgeStart && i < badgeStart + badgeBlock.length) continue;
      if (/\[!\[[^\]]*\]\(https:\/\/img\.shields\.io\//.test(lines[i] ?? "")) {
        say(
          "badges",
          `line ${i + 1} carries a badge outside the row; the house set of badges is the ceiling`,
        );
      }
    }

    const descStart = nextNonBlank(lines, badgeStart + badgeBlock.length);
    const descBlock = blockAt(lines, descStart);
    if (descBlock.length === 0) {
      say("description", "the badge row is not followed by a one-line description paragraph");
    } else if (descBlock.length > 1) {
      say("description", `the description runs ${descBlock.length} lines; it must be one`);
    } else if (/^(?:#|>|\||-|\*|\+|\d+\.|```|~~~)/.test((descBlock[0] ?? "").trim())) {
      say("description", "the badge row is not followed by a plain paragraph");
    } else {
      const found = unescapeMarkdown((descBlock[0] ?? "").trim());
      if (found !== description) {
        say(
          "description",
          `it must be byte-identical to this package's manifest description.\n` +
            `    package.json: ${JSON.stringify(description)}\n` +
            `    README.md:    ${JSON.stringify(found)}`,
        );
      }
    }
  }

  // --- The required sections, in order, License last ------------------------------------------
  const sections = sectionsOf(lines, mask);
  const titles = sections.map((s) => s.title);
  const byTitle = new Map();
  for (const section of sections) {
    if (!byTitle.has(section.title)) byTitle.set(section.title, section);
  }

  let previous = -1;
  for (const required of REQUIRED_HEADINGS) {
    const at = titles.indexOf(required);
    if (at === -1) {
      say("sections", `the required heading \`## ${required}\` is missing`);
      continue;
    }
    if (titles.indexOf(required, at + 1) !== -1) {
      say("sections", `the heading \`## ${required}\` appears more than once`);
    }
    if (at < previous) {
      say(
        "sections",
        `\`## ${required}\` appears before \`## ${REQUIRED_HEADINGS[REQUIRED_HEADINGS.indexOf(required) - 1]}\`; ` +
          `the required headings must appear in the order ${REQUIRED_HEADINGS.join(", ")}`,
      );
    }
    previous = Math.max(previous, at);
  }
  if (titles.length > 0 && titles[titles.length - 1] !== "License") {
    say(
      "sections",
      `\`## License\` must be the last heading; the last one is \`## ${titles[titles.length - 1]}\``,
    );
  }

  /**
   * The text of a required section, or `null` when it is absent.
   *
   * @param {string} title The heading text.
   * @returns {string | null} The section body.
   */
  const bodyOf = (title) => {
    const section = byTitle.get(title);
    if (section === undefined) return null;
    return lines.slice(section.start, section.end).join("\n");
  };

  const status = bodyOf("Status");
  if (status !== null && version.startsWith("0.0.")) {
    const sentence = statusSentence(name);
    const statusLines = status.split("\n").filter((line) => line.trim() !== "");
    if ((statusLines[0] ?? "").trim() !== sentence) {
      say(
        "status",
        `a 0.0.x package's Status section must OPEN with this exact sentence.\n` +
          `    want: ${sentence}\n` +
          `    got:  ${(statusLines[0] ?? "(empty section)").trim()}`,
      );
    }
    if (statusLines.length < 2) {
      say(
        "status",
        "the Status section must also name at least one surface that is still moving or not covered",
      );
    }
    for (const claim of SETTLED_API_CLAIMS) {
      if (claim.test(status)) {
        say(
          "status",
          `it claims a settled or stable public API while the manifest says ${version}. ` +
            `That claim belongs to the 0.1.0 release, not to a 0.0.x package`,
        );
        break;
      }
    }
  }

  const install = bodyOf("Install");
  if (install !== null) {
    if (name !== "" && !install.includes(name)) {
      say("install", `it does not name this package's specifier \`${name}\``);
    }
    if (!install.includes(floor)) {
      say("install", `it does not name this package's effective Node engine floor \`${floor}\``);
    }
  }

  const usage = bodyOf("Usage");
  if (usage !== null && !/^ {0,3}(?:`{3,}|~{3,})/m.test(usage)) {
    say(
      "usage",
      "it carries no fenced code block; a Usage section without a runnable example is not one",
    );
  }

  const phi = bodyOf("PHI and safety");
  if (phi !== null && phi.trim() === "") {
    say(
      "phi",
      "the `## PHI and safety` section is empty. Every README this repository publishes owes the reader an answer",
    );
  }

  const contributing = bodyOf("Contributing");
  if (contributing !== null && !contributing.includes(ISSUES_URL)) {
    say("contributing", `it does not carry the issue tracker ${ISSUES_URL}`);
  }

  const license = bodyOf("License");
  if (license !== null) {
    // Graded against the RENDERED PROSE, not the raw source. The mandated absolute LICENSE link
    // carries the owner's name inside its URL, so a raw search can never fail here; see
    // stripLinkTargets. Labels survive, so `[MIT](https://opensource.org/licenses/MIT)` still names
    // the license, while a section whose only `MIT` or `Cosyte` is an address names neither.
    const prose = stripLinkTargets(license);
    if (!/\bMIT\b/.test(prose)) {
      say("license", "it does not name the MIT license anywhere a reader reads");
    }
    if (!/\bCosyte\b/i.test(prose)) {
      say(
        "license",
        "it does not name the owner, Cosyte. The owner inside the LICENSE link's URL is an address, " +
          "not an attribution",
      );
    }
  }

  // --- Claims the file may not make -----------------------------------------------------------
  //
  // The Node floor is scanned over the whole file EXCEPT the badge row, which is already graded
  // byte-exactly above and carries the floor in its URL-encoded form.
  const badgeRow = new Set();
  if (h1 !== undefined) {
    const taglineStart = nextNonBlank(lines, h1 + 1);
    const badgeStart = nextNonBlank(lines, taglineStart + blockAt(lines, taglineStart).length);
    for (let i = badgeStart; i < badgeStart + blockAt(lines, badgeStart).length; i += 1)
      badgeRow.add(i);
  }
  const wantedVersion = floor.replace(/^[^\d]*/, "");
  for (let i = 0; i < lines.length; i += 1) {
    if (badgeRow.has(i)) continue;
    for (const match of (lines[i] ?? "").matchAll(
      /\bnode\b[^\n]{0,40}?>=\s*`?v?(\d+(?:\.\d+){0,2})/gi,
    )) {
      if ((match[1] ?? "") !== wantedVersion) {
        say(
          "engines",
          `line ${i + 1} states the Node floor \`>=${match[1] ?? ""}\`, which this package's own ` +
            `manifest contradicts: its effective floor is \`${floor}\``,
        );
      }
    }
  }

  for (const [pattern, what] of UMBRELLA_REFERENCES) {
    const match = pattern.exec(text);
    if (match !== null) {
      say(
        "pointers",
        `it references the umbrella meta-repo surface ${JSON.stringify(match[0])} (${what}). ` +
          `A published README may not point a reader at a path only the private meta-repo has`,
      );
    }
  }

  for (const [pattern, what] of CADENCE_CLAIMS) {
    const match = pattern.exec(text);
    if (match !== null) {
      say(
        "cadence",
        `${JSON.stringify(match[0])} asserts ${what}. S0161-release-frequency-policy owns that ` +
          `policy and has not landed, so no README here may state it`,
      );
    }
  }

  return problems;
}

/**
 * Read and parse a JSON file, refusing rather than guessing.
 *
 * @param {string} path Absolute path.
 * @param {string} what What the file is, for the diagnostic.
 * @returns {Record<string, any>} The parsed object.
 */
function readManifest(path, what) {
  let raw;
  try {
    raw = readFileSync(path, "utf8");
  } catch (cause) {
    throw new InvocationError(`cannot read ${what} at ${path}: ${String(cause)}`);
  }
  try {
    const parsed = JSON.parse(raw);
    if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new Error("not a JSON object");
    }
    return parsed;
  } catch (cause) {
    throw new InvocationError(`cannot parse ${what} at ${path}: ${String(cause)}`);
  }
}

/**
 * The workspace's package globs, read out of `pnpm-workspace.yaml`.
 *
 * Read rather than assumed, so the derivation below cannot silently go stale: if this repository
 * ever stops being a flat `packages/*` workspace, this gate REFUSES instead of grading whichever
 * subset the old assumption still happens to find. Deliberately a line reader rather than a YAML
 * one, for the same reason scripts/changeset-guard.mjs is: these gates take no dependency, so they
 * can run before `pnpm install`. A shape this cannot read is reported as unreadable (exit 2), never
 * as an empty workspace and never as fine.
 *
 * @param {string} workspaceRoot Repository root.
 * @returns {string[]} The declared globs.
 */
export function workspaceGlobs(workspaceRoot) {
  const path = join(workspaceRoot, "pnpm-workspace.yaml");
  let raw;
  try {
    raw = readFileSync(path, "utf8");
  } catch (cause) {
    throw new InvocationError(`cannot read the workspace file ${path}: ${String(cause)}`);
  }
  const globs = [];
  let inPackages = false;
  for (const rawLine of raw.split("\n")) {
    const line = rawLine.replace(/\s+$/, "");
    if (line.trim() === "" || line.trim().startsWith("#")) continue;
    if (/^packages:\s*$/.test(line)) {
      inPackages = true;
      continue;
    }
    if (!inPackages) continue;
    const item = /^ {2,}- +["']?([^"'\s]+)["']?\s*$/.exec(line);
    if (item === null) break;
    globs.push(item[1] ?? "");
  }
  if (globs.length === 0) {
    throw new InvocationError(
      `${path} declares no \`packages:\` globs this reader can see. Refusing to grade READMEs ` +
        `against a workspace it cannot ground on, which would clear every package it failed to find.`,
    );
  }
  return globs;
}

/**
 * Every governed README: the repository root plus each `packages/*` member.
 *
 * DERIVED, never hardcoded (AC11). A directory under `packages/` that carries a `package.json` is
 * in the governed set by construction, so a tenth package cannot be added without a README: it
 * arrives as a refusal rather than as a skip.
 *
 * @param {string} workspaceRoot Repository root.
 * @returns {{ label: string, readmePath: string, manifest: Record<string, any> }[]} The set.
 */
export function governedReadmes(workspaceRoot) {
  const globs = workspaceGlobs(workspaceRoot);
  if (globs.length !== 1 || globs[0] !== "packages/*") {
    throw new InvocationError(
      `pnpm-workspace.yaml declares ${JSON.stringify(globs)}, not the flat \`packages/*\` layout ` +
        `this gate derives its governed set from. Refusing to grade a subset of the workspace and ` +
        `report clean: teach this script the new layout instead.`,
    );
  }

  const entries = [{ label: "README.md", dir: workspaceRoot }];

  const packagesDir = join(workspaceRoot, "packages");
  let names;
  try {
    names = readdirSync(packagesDir).sort();
  } catch (cause) {
    throw new InvocationError(`cannot read ${packagesDir}: ${String(cause)}`);
  }
  for (const entry of names) {
    const dir = join(packagesDir, entry);
    const manifestPath = join(dir, "package.json");
    let hasManifest = false;
    try {
      hasManifest = statSync(manifestPath).isFile();
    } catch {
      hasManifest = false;
    }
    if (!hasManifest) {
      // A directory carrying a README but NO manifest is a premise this checker cannot ground: the
      // README is plainly meant to be published and there is nothing to grade its description,
      // version, privacy or engine floor against. Skipping it would report clean over a file nobody
      // checked, so it refuses instead. A directory with neither is not a workspace member and is
      // genuinely none of this gate's business.
      let strayReadme = false;
      try {
        strayReadme = statSync(join(dir, "README.md")).isFile();
      } catch {
        strayReadme = false;
      }
      if (strayReadme) {
        throw new InvocationError(
          `packages/${entry}/ carries a README.md but no package.json, so there is nothing to ` +
            `grade its description, version and engine floor against. Refusing to skip it: a ` +
            `README this gate cannot ground is not a README this gate has cleared.`,
        );
      }
      continue;
    }
    entries.push({ label: `packages/${entry}/README.md`, dir });
  }

  if (entries.length === 1) {
    throw new InvocationError(
      `no packages found under ${packagesDir}. Refusing to report clean over a workspace with no ` +
        `members, which would clear every one of them.`,
    );
  }

  return entries.map((entry) => ({
    label: entry.label,
    readmePath: join(entry.dir, "README.md"),
    manifest: readManifest(join(entry.dir, "package.json"), `the manifest for ${entry.label}`),
  }));
}

/**
 * Run the check over a workspace.
 *
 * @param {{ workspaceRoot: string }} options Where to look.
 * @returns {{ ok: boolean, checked: number, report: string[] }} Result and the lines to print.
 */
export function check({ workspaceRoot }) {
  const rootManifest = readManifest(join(workspaceRoot, "package.json"), "the root manifest");
  const rootEngines = rootManifest.engines;
  const rootFloor =
    rootEngines !== null && typeof rootEngines === "object" && typeof rootEngines.node === "string"
      ? rootEngines.node
      : null;
  if (rootFloor === null) {
    throw new InvocationError(
      `the root package.json declares no \`engines.node\`, which is the fallback Node floor every ` +
        `package without its own one reports. Refusing to grade engine claims against a floor that ` +
        `does not exist.`,
    );
  }

  const governed = governedReadmes(workspaceRoot);
  const report = [];
  let bad = 0;

  for (const entry of governed) {
    let text;
    try {
      text = readFileSync(entry.readmePath, "utf8");
    } catch (cause) {
      throw new InvocationError(
        `cannot read the governed README ${entry.label}: ${String(cause)}. Every package this ` +
          `workspace carries owes a README, so an absent one is a refusal and never a skip.`,
      );
    }
    const problems = gradeReadme({
      label: entry.label,
      text,
      manifest: entry.manifest,
      floor: effectiveFloor(entry.manifest, rootFloor),
    });
    // Every offending file is reported, in one run. Stopping at the first would turn a nine-file
    // sweep into nine pushes.
    if (problems.length === 0) continue;
    bad += 1;
    for (const problem of problems) report.push(`ERROR: ${problem}`);
  }

  if (bad > 0) {
    report.push(
      "",
      `Refusing: ${bad} of ${governed.length} governed README(s) do not carry the house skeleton.`,
      `The skeleton is process/templates/readme.md, carried into this repo by this gate: banner, H1,`,
      `tagline, badge row, the manifest description, then ${REQUIRED_HEADINGS.map((h) => `## ${h}`).join(", ")}.`,
      `A README is inside each package's \`files\` array, so a wrong string here is frozen into the`,
      `npm tarball at the next publish and correctable only by publishing again.`,
    );
    return { ok: false, checked: governed.length, report };
  }

  return {
    ok: true,
    checked: governed.length,
    report: [`readme-check: OK (${governed.length} governed README(s) carry the house skeleton)`],
  };
}

/**
 * CLI entry point.
 *
 * @param {string[]} argv Arguments after the script path.
 * @returns {number} Process exit code.
 */
function main(argv) {
  let workspaceRoot = process.cwd();
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--workspace") {
      i += 1;
      const value = argv[i];
      if (value === undefined) throw new InvocationError("--workspace needs a value");
      workspaceRoot = value;
    } else {
      throw new InvocationError(`unknown argument ${JSON.stringify(arg)}`);
    }
  }

  const result = check({ workspaceRoot: resolve(workspaceRoot) });
  const stream = result.ok ? process.stdout : process.stderr;
  for (const line of result.report) stream.write(`${line}\n`);
  return result.ok ? 0 : 1;
}

// `isCliEntrypoint` is what keeps importing this file for tests from executing the CLI, and the
// InvocationError handler is what keeps a broken invocation on exit 2: left to node's default an
// uncaught throw exits 1, which is the code this contract reserves for "a README violates the
// skeleton", and the two must not be the same signal.
if (isCliEntrypoint(import.meta.url)) {
  try {
    process.exit(main(process.argv.slice(2)));
  } catch (error) {
    if (error instanceof InvocationError) {
      process.stderr.write(`ERROR: readme-check could not run: ${error.message}\n`);
      process.exit(2);
    }
    throw error;
  }
}
